AUDIO_PATH = "None"
VIDEO_PATH = "video/test_video_1.mp4"
USE_AUDIO = False # separate audio file
USE_VIDEO = True
VIDEO_AUDIO_ON = False
RECORDING_ON = False
RECORDINGS_FOLDER = "/home/pi/sakis-video-tunnel/camera-records/"
DOCNAME = "Monkey-logs"
IX_SHEET = "main-logs"
ALIVE_SHEET = "alive-logs"
PROGRUN_SHEET = "prog-run-logs"
SENSOR_SHEET = "sensor-log"
TEST_PHASE = "testing"
